# Generated by Django 2.1 on 2020-11-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=None)),
                ('station_name', models.CharField(default=None, max_length=999)),
                ('lat', models.FloatField(default=0.0)),
                ('lon', models.FloatField(default=0.0)),
                ('dist_to_office', models.FloatField(default=None)),
                ('dist_to_partners_office', models.FloatField(default=None)),
                ('access', models.FloatField(default=None)),
                ('landPrice', models.FloatField(default=None)),
                ('park', models.FloatField(default=None)),
                ('flood', models.FloatField(default=None)),
                ('security', models.FloatField(default=None)),
                ('score', models.FloatField(default=None)),
            ],
        ),
    ]
