# Generated by Django 2.1 on 2020-11-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokosumi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultrank',
            name='partners_station_name',
            field=models.CharField(default=None, max_length=999),
        ),
    ]
